# Generated by Django 5.0.6 on 2024-06-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_door',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_luggage_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_year',
        ),
    ]
