# Generated by Django 5.0.6 on 2024-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vehicle_vehicle_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='licence_picture',
            field=models.ImageField(blank=True, null=True, upload_to='licence_pictures/'),
        ),
    ]
