# Generated by Django 5.0.4 on 2024-06-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_days',
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
