# Generated by Django 5.0.6 on 2024-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_booking_total_days_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
