# Generated by Django 5.0.6 on 2024-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_approved_vehicle_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='licence_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='licence_pictures/'),
        ),
    ]
