# Generated by Django 5.0.6 on 2024-06-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_licence_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingTransaction',
        ),
    ]
