# Generated by Django 5.0.6 on 2024-06-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_bookinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingHistory',
        ),
    ]
